[{"bug_class":"","kind":"ERROR","bug_type":"Bad_footprint","qualifier":".","severity":"LOW","visibility":"developer","line":18,"column":8,"procedure":"main","procedure_id":"main.fad58de7366495db4650cfefac2fcd61","procedure_start_line":7,"file":"alias.c","bug_trace":[{"level":0,"filename":"alias.c","line_number":7,"column_number":1,"description":"start of procedure main()"},{"level":0,"filename":"alias.c","line_number":10,"column_number":3,"description":""},{"level":0,"filename":"alias.c","line_number":11,"column_number":3,"description":""},{"level":0,"filename":"alias.c","line_number":18,"column_number":3,"description":""}],"key":"alias.c|main|Bad_footprint","node_key":"8837ec90eed939cf91937d91e4f3c434","hash":"c3084bc589dfe68153f84a6a7aef1210","infer_source_loc":{"file":"biabduction/Rearrange.ml","lnum":306,"cnum":38,"enum":45},"bug_type_hum":"Bad Footprint","censored_reason":""},{"bug_class":"PROVER","kind":"ERROR","bug_type":"MEMORY_LEAK","qualifier":"memory dynamically allocated by call to `malloc()` at line 11, column 12 is not reachable after line 18, column 3.","severity":"HIGH","visibility":"user","line":18,"column":3,"procedure":"main","procedure_id":"main.fad58de7366495db4650cfefac2fcd61","procedure_start_line":7,"file":"alias.c","bug_trace":[{"level":0,"filename":"alias.c","line_number":7,"column_number":1,"description":"start of procedure main()"},{"level":0,"filename":"alias.c","line_number":10,"column_number":3,"description":""},{"level":0,"filename":"alias.c","line_number":11,"column_number":3,"description":""},{"level":0,"filename":"alias.c","line_number":18,"column_number":3,"description":""}],"key":"alias.c|main|MEMORY_LEAK","node_key":"8837ec90eed939cf91937d91e4f3c434","hash":"39e22af65f4ca2f5ba0c6972404987e5","infer_source_loc":{"file":"biabduction/Abs.ml","lnum":1082,"cnum":18,"enum":25},"bug_type_hum":"Memory Leak","censored_reason":""}]
